name = "HTTPPlayback"
uuid = "bdd55f5b-6e67-4da1-a080-6086e55655a0"
authors = ["Chris de Graaf <me@cdg.dev> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
